AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
    EmojiToTextFunction:
        Type: AWS::Serverless::Function
        Properties:
            PackageType: Image
            Architectures:
                - x86_64
        Metadata:
            DockerTag: python3.8-v1
            DockerContext: .
            Dockerfile: Dockerfile
